src/apps/zavrel/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views



app_name = 'zavrel'
urlpatterns = [
	# url(r'^search.html$', views.search, name='search', kwargs={'page': "search"}),
	# url(r'^def/(?P<permalink>.+)$', views.funpage, name='fun_detail'),
	url(r'^pages/(?P<page>[\w-]+)/$', views.index, name='pages'),
	url(r'^index$', views.index, name='index'),
	url(r'^$', RedirectView.as_view(url='/index'), name="home"),


]
	

src/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView


admin.site.site_header = 'Administration'
admin.site.site_title = 'Zavrel'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^zavrel/', include('extempore.urls')),
    url(r'', include('zavrel.urls')),

    # EXAMPLE OF REDIRECT
    # url(
    #     r'^',
    #     RedirectView.as_view(
    #         pattern_name='dbpedialinks:home', permanent=False)),
    
]

src/apps/zavrel/models.py
from django.db import models
from django.contrib import admin
from django.urls import reverse

import datetime
import urllib
# 
import myutils.abstract_models as mymodels


def nice_url_name(s):
	return urllib.parse.quote_plus(s)


# class XTMFundocEntry(mymodels.EnhancedModel):
# 	"""(XTMFundocEntry enhanced model - timestamps and creation fields inherited)"""
	
# 	name = models.CharField(blank=True, max_length=200, verbose_name="name")
# 	url = models.CharField(blank=True, max_length=350, verbose_name="url", help_text="URL to the github page for this function") 
# 	permalink = models.CharField(blank=True, max_length=350, verbose_name="permalink", help_text="Unique name to be used in the for this function")
# 	source = models.TextField(blank=True, verbose_name="implementation")
# 	fungroup = models.CharField(blank=True, max_length=350, verbose_name="group eg by prefix normally")
# 	funtype = models.CharField(blank=True, max_length=350, verbose_name="type eg whether r a macro or scheme function or xtlang")	
# 	is_custom = models.BooleanField(default=False, verbose_name="custom function?",
# 		help_text="Whether this function is a custom one, not from the official Extempore codebase.")	
	
# 	# unused for now
# 	desc = models.TextField(blank=True, verbose_name="desc")
# 	signature = models.CharField(blank=True, max_length=300, verbose_name="signature")
# 	examples = models.TextField(blank=True, verbose_name="examples")
# 	args = models.TextField(blank=True, verbose_name="args")
# 	returns = models.CharField(blank=True, max_length=300, verbose_name="returns")	
# 	related = models.CharField(blank=True, max_length=300, verbose_name="related")
	
# 	class Admin(admin.ModelAdmin):
# 		readonly_fields=('created_at', 'updated_at')
# 		list_display = ('id', 'name', 'is_custom', 'funtype', 'fungroup', 'updated_at')
# 		list_display_links = ('id', 'name',)
# 		search_fields = ['id', 'name', 'desc']
# 		list_filter = ('created_at', 'updated_at', 'created_by', 'editedrecord', 'is_custom', 'review', 'funtype', 'fungroup')
# 		#filter_horizontal = (,) 
# 		#related_search_fields = { 'fieldname': ('searchattr_name',)}
# 		#inlines = (inlineModel1, inlineModel2)
# 		fieldsets = [
# 			('Administration',	
# 				{'fields':	
# 					['editedrecord', 'review', 'internal_notes', ('created_at', 'created_by'), 
# 					  ('updated_at', 'updated_by')
# 					 ],	 
# 				'classes': ['collapse']
# 				}),
# 			('',	
# 				{'fields':	
# 					['name', 'url', 'source', 'is_custom', 'desc', 'fungroup', 'funtype', 'signature', 'examples', 'args', 'returns', 'related'
# 					 ],	 
# 				# 'classes': ['collapse']
# 				}),	
# 			]
# 		#class Media:
# 			#js = ("js/admin_fixes/fix_fields_size.js",)
			
# 		def save_model(self, request, obj, form, change):
# 			"""adds the user information when the rec is saved"""
# 			if getattr(obj, 'created_by', None) is None:
# 				  obj.created_by = request.user
# 			obj.updated_by = request.user
# 			obj.save()	
			

# 	def get_namespace(self):
# 		if self.fungroup:
# 			return self.fungroup
# 		else:
# 			return " top level"

# 	def get_absolute_url(self):        
# 		return reverse('extempore:fun_detail', kwargs={'permalink': self.permalink})

# 	def save(self, *args, **kwargs):
# 		"""Generate a permalink for the entry."""
# 		super(XTMFundocEntry, self).save(*args, **kwargs)
# 		if not self.permalink:
# 			self.permalink = nice_url_name(self.name.replace(":", "-"))
# 			super(XTMFundocEntry, self).save(*args, **kwargs)


# 	@classmethod
# 	def cleanup_permalinks(self, *args, **kwargs):
# 		"""Ensure each permalink is unique.
# 		If two functions have the same name, add a number to the end.
# 		NOTE run this utility after data input is complete.
# 		"""

# 		for each in self.objects.all().order_by('-id'):

# 			test = XTMFundocEntry.objects.filter(permalink=each.permalink).count()

# 			if test > 1:
# 				each.permalink = f"{each.permalink}-{test-1}"
# 				print("DUPLICATE EXISTS FOR FUNCTION", each.name, " => New permalink:", each.permalink)
# 				each.save()


# 	class Meta:
# 		verbose_name_plural="XTM Functions"
# 		verbose_name = "XTM Function"
# 		ordering = ["id"]
		
# 	def __unicode__(self):
# 		return "XTM Function %d" % self.id
	

src/apps/zavrel/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

import time
import os

from settings import SITE_ROOT
from .models import *

def index(request, page=""):
	
	t = get_text()
	allpages_no = len(t)
	is_last = False

	try:
		# single page
		page_no = int(page)
		if allpages_no == page_no:
			is_last = True
		page_data = (page_no, t[page_no])
		nextpage_no = page_no + 1
		if nextpage_no > 19:
			nextpage_no = 1
	except:
		# index page
		page_data = None
		nextpage_no = None

	print("Page: ", page_data)

	context = {	
		'alltext' : t , 
		'page' : page_data,
		'nextpage_no' : nextpage_no, 
		'allpages_no' : allpages_no,
		'is_last' : is_last 
		}

	return render(request, "zavrel/home.html", context)





def get_text(number=None):
	"""Read simple markdown file and spit out a dictionary with the text
		{1 : "...", 2 : "...."} etc..
	"""
	with open(os.path.join(SITE_ROOT, "src", "static", "thetext.md")) as f:
		text = f.readlines()

	data = {}

	#
	# Read source file
	# Newlines are preserved as <br />
	# '#' sign is used to delimit a page 
	#
	linenumber = 0
	buffertext = ""
	for x in text:
		if x == "\n" and not buffertext: 
			# skip first empty line
			continue
		elif x[0] == "#":  
			# new page: save buffer and zero variables
			if linenumber:
				data[linenumber] = buffertext
			linenumber += 1
			buffertext = ""
		else: 
			# load buffer
			buffertext += x.replace("\n", "<br />")
	

	try:
		return data[number]
	except:
		return data

src/apps/zavrel/templates/zavrel/base.html
{# Bootstrap 3.3.7 #}

{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>

	{% include 'zavrel/ga.html' %}



    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" href="{% static 'favicon.ico' %} ">
    
	{% block pagetitle %}
		<title>Zavrel Dreams</title>
	{% endblock pagetitle %}
	

    <!-- Bootstrap ## original specs-->
    {# <link href="{{ STATIC_URL }}libs/bootstrap-3.2.0-dist/css/bootstrap.min.css" rel="stylesheet"> #}
	
	<!-- Bootswatch https://bootswatch.com/ -->
	 <link href="{% static 'libs/bootswatch3.2/flatly/bootstrap.min.css' %}" rel="stylesheet">
	 

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
		
		
	<style type="text/css" media="screen">


		/* Sticky footer styles 
		-------------------------------------------------- */
		html {
		  position: relative;
		  min-height: 100%;
		}
		body {
		  /* Margin bottom by footer height */
		  margin-bottom: 600px;
		  padding-top: 100px;
		}
		.footer {
		  position: absolute;
		  padding-top: 20px;
		  bottom: 0;
		  width: 100%;
		  font-size: 18px;
		  /* Set the fixed height of the footer here */
		  height: 300px;
		  background-color: #f5f5f5;
		}
		

		.navbar-subtitle.navbar-brand {
			color: #ffffff;
			font-style: normal;
		}

		.navbar-function {
			color: lightgreen;
			font-style: normal;
			font-family: monospace;
		}
		.navbar-function:hover {
			color: lightgreen;
			font-style: normal;
			font-family: monospace;
			text-decoration: none;
		}
		
		.navbar-subtitle.navbar-brand a {
			color: #ffffff;
			font-style: normal;
			text-decoration: underline;
		}

		.navbar-subtitle.navbar-brand a.active {
			background: green;
			font-style: normal;
			text-decoration: underline;
		}

		.navbar-subtitle.navbar-brand:hover {
			color: #ffffff;
			font-style: normal;
		}

		a.quietlink {
			color: inherit
		}
		a.quietlink:hover {
			color: #18bc9c;
		}

		.lead {
			font-size: 30px;
			color: #2c3e50cf;
		}


	</style>	
		
		
	
	{% block extrahead %}

	{% endblock extrahead %}	
		
		
  </head>
  <body>
	  
	
	
	{% block navbar %}
	
	{% endblock navbar %}  

	  
	  <div class="container">
	  	{% block bodycontent %}
		
	  		<h1>Hello, world!</h1>
	  	{% endblock bodycontent %}

	  </div>
	  
	  
  	<div class="footer">
  		{% block footer %}
		

  	  <div class="container">
		<a name="aboutsite"></a>
		<h2>About</h2>

		<p><a target="_blank" href="https://www.amazon.it/sogno-Venezia-Step%C3%A1n-Zavrel/dp/8895818504">A Dream in Venice</a> is a children story from <a href="https://fondazionezavrel.it/en/stepan-zavrel/">Štěpán Zavřel</a>. Originally written in italian, I couldn't read it to my childrens' classroom so I made this website and translated it from the original language as best as I could (suggestions for improvements are <a href="https://www.michelepasin.org/contact.html">welcome!</a>)</p> 

		<h3>This website</h3>

		<p>The source code for this website is written in Python and is also available on <a href="https://github.com/lambdamusic/zavrel-dream" target="_blank">GitHub</a>.</p> 

		<p>This project was created by <a href="https://www.michelepasin.org/" target="_blank">Michele Pasin</a>.</p> 



  	  </div>
	  
		

  	  {% endblock footer %}
  	</div>

	  
	  
	  
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'libs/bootstrap-3.2.0-dist/js/bootstrap.min.js' %}"></script>
	

	<script src="https://unpkg.com/lunr/lunr.js"></script>

	{% block global_js  %}

	{% endblock  %}
	
	
	
  </body>
</html>

src/apps/zavrel/templates/zavrel/ga.html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-T4B4FDV3TR"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-T4B4FDV3TR');
</script>

src/apps/zavrel/templates/zavrel/home.html
{% extends "zavrel/base.html" %}
{% load static %}
{# {% load ontotags %} #}

{% block navbar %}

	{% include 'zavrel/navbar.html' %}

{% endblock navbar %}





{% block bodycontent %}



<div class="row">


	
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		
		<h1><a class="quietlink" href="{% url 'zavrel:home' %}">A Dream in Venice</a></h1>

		<p>by Štěpán Zavřel</p>


		
		{% if page %}
		<!-- SINGLE PAGE -->

		<div class="row">

			<hr>

			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
				<h4>{{page.0}}</h4>
				<p class="lead">{{page.1|safe}}</p>

				{% if is_last %}
				<p class="text-left" style="margin-top: 5px;"><a title="Back to index" href="{% url 'zavrel:home' %}">the end</a></p>
				{% else %}
				<p class="text-left" style="margin-top: 5px;"><a title="Open the next page" href="{% url 'zavrel:pages' nextpage_no %}">next&rarr;</a></p>
				{% endif %}

				
			</div>
		
			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
				
				{% if is_last %}
				<a href="{% url 'zavrel:home' %}">
				{% else %}
				<a href="{% url 'zavrel:pages' nextpage_no %}">
				{% endif %}
					
					<img src="{% static '' %}img/page{{page.0}}.jpeg" class="img-responsive" alt="Image" width="100%;">
				</a>

				<p class="text-right" style="margin-top: 5px;"><a href="{% static '' %}img/page{{page.0}}.jpeg">view full-size</a></p>
			</div>

		</div>

			
		{% else %}
		<!-- BOOK INDEX  -->

		<div class="row">
			<hr>

			<div class="container">
			

				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						{% for n, t in alltext.items  %}
						<a class="quietlink" href="{% url 'zavrel:pages' n %}"><b>{{n}}</b>&nbsp;<span class="">{{t|striptags|truncatewords:10}}</span></a><br />
						{% endfor %}
					</div>
				
					
					<div class="col-xs-4 col-sm-4 col-md-6 col-lg-4">
						<a href="{% url 'zavrel:pages' 1 %}">
							<img src="{% static '' %}img/bookcover.jpeg" class="img-responsive" alt="Image">
						</a>
						<p class="text-right" style="margin-top: 5px;"><a href="{% static '' %}img/bookcover.jpeg">view full-size</a></p>
					</div>

				</div>

				
			
			</div>

		</div>
			
		{% endif %}
			


		

	</div>
	


</div> <!-- end of row -->




<div class="row">
	&nbsp;
	<br />
	&nbsp;
</div>


{% endblock bodycontent %}

src/apps/zavrel/templates/zavrel/navbar.html
<!-- https://getbootstrap.com/docs/3.4/components/#navbar -->

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Zavrel Dreams</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#aboutsite">About</a></li>

        
        {% comment %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        {% endcomment %}

      </ul>
      {% comment %}
      <form id="searchForm" class="navbar-form navbar-right" method="GET">
        <div class="form-group">
          <input type="text" style="width: 350px;" class="form-control " placeholder="Search" required type="search" name="q">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>


      <script>
        var loc = location.origin;
        document.getElementById("searchForm").action = loc + "/search.html";
      </script>
      {% endcomment %}

      <a style="display: none;" href="{% url 'zavrel:home'%}">hidden link</a>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>